# Generated by Django 4.1.13 on 2024-05-02 14:24

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video Stream',
                'verbose_name_plural': 'Video Streams',
            },
        ),
        migrations.CreateModel(
            name='CameraStream',
            fields=[
                ('videostream_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='camera.videostream')),
                ('url', models.TextField()),
            ],
            options={
                'verbose_name': 'Camera Stream',
                'verbose_name_plural': 'Camera Streams',
            },
            bases=('camera.videostream',),
        ),
    ]
