# Generated by Django 4.1.13 on 2024-04-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video Stream',
                'verbose_name_plural': 'Video Streams',
            },
        ),
        migrations.CreateModel(
            name='CameraStream',
            fields=[
                ('videostream_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='detect_violence.videostream')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Camera Stream',
                'verbose_name_plural': 'Camera Streams',
            },
            bases=('detect_violence.videostream',),
        ),
        migrations.CreateModel(
            name='RecordedVideo',
            fields=[
                ('videostream_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='detect_violence.videostream')),
                ('path', models.TextField()),
            ],
            options={
                'verbose_name': 'Recorded Video',
                'verbose_name_plural': 'Recorded Videos',
            },
            bases=('detect_violence.videostream',),
        ),
    ]
