# Generated by Django 4.1.13 on 2024-05-06 12:44

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Secteur ',
                'verbose_name_plural': 'Secteur ',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('longitude', models.TextField(blank=True)),
                ('latitude', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.secteur')),
            ],
            options={
                'verbose_name': 'Camera Stream',
                'verbose_name_plural': 'Camera Streams',
            },
        ),
    ]
